# Generated by Django 4.1.7 on 2023-04-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
                ('name', models.CharField(max_length=50, verbose_name='Бренд')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес автосалона')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон автосалона')),
                ('main_picture', models.ImageField(upload_to='main models', verbose_name='Фото на главной странице моделей')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'класс авто',
                'verbose_name_plural': 'Классы авто',
            },
        ),
        migrations.CreateModel(
            name='Drive_unit',
            fields=[
                ('id_drive_unit', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип привода')),
            ],
            options={
                'verbose_name': 'тип привода',
                'verbose_name_plural': 'Типы привода',
            },
        ),
        migrations.CreateModel(
            name='Fuel_type',
            fields=[
                ('id_fuel_type', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('card_pictures', models.ImageField(upload_to='model', verbose_name='Фото для карточки')),
                ('description', models.TextField(verbose_name='Описание авто')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.brand', verbose_name='Бренд')),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.class', verbose_name='Класс авто')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id_transmission', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип трансмиссии')),
            ],
            options={
                'verbose_name': 'тип трансмиссии',
                'verbose_name_plural': 'Типы трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id_modification', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.FloatField(max_length=5, verbose_name='Объем двигателя')),
                ('engine_power', models.IntegerField(max_length=5, verbose_name='Мощность двигателя')),
                ('id_drive_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.drive_unit', verbose_name='Тип привода')),
                ('id_fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.fuel_type', verbose_name='Тип топлива')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.model', verbose_name='Модель')),
                ('id_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.transmission', verbose_name='Тип трансмиссии')),
            ],
            options={
                'verbose_name': 'модификацию',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.CreateModel(
            name='Model_picture',
            fields=[
                ('id_model_picture', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_1', models.ImageField(upload_to='model picture', verbose_name='Главное изображение')),
                ('picture_2', models.ImageField(upload_to='model picture', verbose_name='Второстепенное изображение')),
                ('picture_3', models.ImageField(upload_to='model picture', verbose_name='Второстепенное изображение')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'изображение модели',
                'verbose_name_plural': 'Изображения моделей',
            },
        ),
        migrations.CreateModel(
            name='Car_equipment',
            fields=[
                ('id_car_equipment', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комплектации')),
                ('description', models.TextField(verbose_name='Описание комплектации')),
                ('price', models.IntegerField(verbose_name='Цена комплектации')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'комплектацию',
                'verbose_name_plural': 'Комплектации',
            },
        ),
    ]
