# Generated by Django 4.1.7 on 2023-04-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'бренд', 'verbose_name_plural': '1. Бренды'},
        ),
        migrations.AlterModelOptions(
            name='car_equipment',
            options={'verbose_name': 'комплектацию', 'verbose_name_plural': '5. Комплектации'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'класс авто', 'verbose_name_plural': '6. Классы авто'},
        ),
        migrations.AlterModelOptions(
            name='drive_unit',
            options={'verbose_name': 'тип привода', 'verbose_name_plural': '9. Типы привода'},
        ),
        migrations.AlterModelOptions(
            name='fuel_type',
            options={'verbose_name': 'тип топлива', 'verbose_name_plural': '7. Типы топлива'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'модель', 'verbose_name_plural': '2. Модели'},
        ),
        migrations.AlterModelOptions(
            name='model_picture',
            options={'verbose_name': 'изображение модели', 'verbose_name_plural': '3. Изображения моделей'},
        ),
        migrations.AlterModelOptions(
            name='modification',
            options={'verbose_name': 'модификацию', 'verbose_name_plural': '4. Модификации'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'тип трансмиссии', 'verbose_name_plural': '8. Типы трансмиссий'},
        ),
    ]
