# Generated by Django 4.1.7 on 2023-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_brand_options_alter_car_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='engine_power',
            field=models.IntegerField(verbose_name='Мощность двигателя'),
        ),
    ]
