# Generated by Django 4.1.7 on 2023-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_modification_engine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='engine_power',
            field=models.IntegerField(max_length=5, verbose_name='Мощность двигателя'),
        ),
    ]
