# Generated by Django 4.1.7 on 2023-05-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_operating_tips_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Область/Регион')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': '2. Области и регионы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название города')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент города')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.region', verbose_name='Область/Регион')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': '3. Города',
            },
        ),
    ]
