# Generated by Django 4.1.7 on 2023-05-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('client_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': '2. Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('client_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.BooleanField(verbose_name='Статус обработки')),
            ],
            options={
                'verbose_name': 'запрос',
                'verbose_name_plural': '1. Запросы',
            },
        ),
    ]
