# Generated by Django 4.1.7 on 2023-05-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_car_in_stock_engine_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body_type',
            options={'verbose_name': 'тип кузова', 'verbose_name_plural': '2. Типы кузова'},
        ),
    ]
