# Generated by Django 4.1.7 on 2023-05-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_body_type_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_in_stock',
            options={'verbose_name': 'автомобили на складе', 'verbose_name_plural': '1. Автомобили на складе'},
        ),
    ]
